// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  communities: dynamic(() => import("./Communities")),
  hero: dynamic(() => import("./Hero")),
};
